# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    nbResults: 5
    prefix: '%env(APP_ENV)%_'
    doctrineSubscribedEvents: []
    indices:
        - name: slots
          class: App\Entity\Slot
          enable_serializer_groups: true
