framework:
    notifier:
        chatter_transports:
            telegram: 'telegram://%env(TELEGRAM_TOKEN)%@default'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }

when@test:
    framework:
        notifier:
            chatter_transports:
                telegram: 'null://dev'
