name: Pipeline

on: pull_request

jobs:
    build:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Cache Vendors
              uses: actions/cache@v1
              id: cache-vendors
              with:
                path: vendor
                key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock')}}
            - name: Composer Validation
              run: composer validate --strict
            - name: Install PHP Dependencies
              run: composer install --no-scripts
            - name: Lint Yaml Files
              run: bin/console lint:yaml config --parse-tags
            - name: Code Style PHP
              run: vendor/bin/php-cs-fixer fix --dry-run
            - name: Cache PHPUnit
              uses: actions/cache@v1
              id: cache-phpunit
              with:
                path: bin/.phpunit
                key: ${{ runner.os }}-phpunit-${{ hashFiles('**/phpunit.xml.dist')}}
            - name: Tests
              run: bin/phpunit
            - name: Static Code Analysis
              run: vendor/bin/phpstan analyse
